---
ID: "9a6e8bac-8dcc-58e6-ae06-b70c5cf77f06"
Parent: "21f8c6a4-9b49-52c9-8542-898f372879ae"
Template: "21f8c6a4-9b49-52c9-8542-898f372879ae"
Path: "/sitecore/templates/Project/molina/Styleguide-ContentList-Item-Template/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T051617Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
