---
ID: "5abf85c1-1a0c-5098-8ff3-f1d0f315c56e"
Parent: "4d70a594-4bb3-5156-ac52-a973b15f3f28"
Template: "4d70a594-4bb3-5156-ac52-a973b15f3f28"
Path: "/sitecore/templates/Project/molina/Styleguide-FieldUsage-Text/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T051622Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
