---
ID: "d62eed93-aa96-5030-8dd9-4c1d6464d96f"
Parent: "7073edc0-24ce-5f45-8d60-e331af3e85cb"
Template: "7073edc0-24ce-5f45-8d60-e331af3e85cb"
Path: "/sitecore/templates/Project/molina/Styleguide-Layout-Reuse/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T051622Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
