---
ID: "33961709-f512-5cce-acbe-995544ae8be9"
Parent: "fca4deb0-1a53-59a6-8be8-e349ab9250cb"
Template: "fca4deb0-1a53-59a6-8be8-e349ab9250cb"
Path: "/sitecore/templates/Project/molina/Styleguide-FieldUsage-RichText/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T051622Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
