---
ID: "416d0ccc-8135-521c-a1af-9671c43ed11e"
Parent: "211b7ee1-bc8d-5f95-b8b1-99d761856bbc"
Template: "211b7ee1-bc8d-5f95-b8b1-99d761856bbc"
Path: "/sitecore/templates/Project/molina/Styleguide-FieldUsage-Date/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T051620Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
