---
ID: "f64df4df-4be4-5dee-988f-8b37a4e73f1c"
Parent: "b7282e46-64d9-509e-b198-15585bcdc655"
Template: "b7282e46-64d9-509e-b198-15585bcdc655"
Path: "/sitecore/templates/Project/molina/Styleguide-Layout-Tabs-Tab/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T051623Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
