---
ID: "8e4358d7-b636-5e9a-aabe-3cb3eccb3d2b"
Parent: "1443c31a-b8fc-534f-89df-fef0643e960f"
Template: "1443c31a-b8fc-534f-89df-fef0643e960f"
Path: /sitecore/templates/Project/molina/ExampleCustomRouteType/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T051616Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
